
console.log("=== IF - ELSE ===")
const numero = 10

 if (isNaN(numero)) {
        console.log("Entrada invalida, no es un numero");
        return;
    } else if (numero % 2 === 0){
        console.log("es par, Bien");
    } else {
        console.log("es impar, Bien");
    }

    //switch 
    console.log("=== switch ===")

    switch (key) {
        case value:
            
            break;
    
        default:
            break;
    }